### ISSUE TITLE
To-do list for PureChat v1.4.0

### ISSUE THREAD

**Issue by 64FF00** [PurePlugins/PureChat#16]
### New Features
- [x] Add {faction_name} and {faction_rank} tags for displaying only faction names or player faction ranks (@AryToNeX)
- [x] API for Setting Chat Formats + Nametags (https://github.com/PurePlugins/PureChat/issues/36)
- [x] Custom Prefixes (@AryToNeX)
- [ ] Per-world / Global Chat (https://github.com/PurePlugins/PureChat/issues/24)

**Comment by JoahDave** [comment]
Yay! Colorful tags!

**Comment by xpyctum** [comment]
MySQL ? :D

**Comment by xXCyrerXx** [comment]
{HEALTHY} :D

**Comment by AryToNeX** [comment]
@xXCyrerXx :+1:

**Comment by Pub4Game** [comment]
To do so would have sent the message was written in NameTag, as implemented in the PC version

**Comment by Pub4Game** [comment]
@64FF00 When will PureChat 1.4?

**Comment by 64FF00** [comment]
@Pub4Game Very soon. :+1:

**Comment by Pub4Game** [comment]
@64FF00 Faster would add custom prefixes :D

**Comment by Pub4Game** [comment]
@64FF00 Add the prefixes, they will be useful) I've been waiting and still no

**Comment by DRedDogPE** [comment]
Factions dont show in chat :( just '...'

**Comment by Pub4Game** [comment]
@64FF00 Please make Custom Prefixes! Already so much time has passed....

**Comment by 64FF00** [comment]
@Pub4Game Already working on it. :+1:

**Comment by Pub4Game** [comment]
@64FF00 Yay! <3

**Comment by 64FF00** [comment]
@Pub4Game done :)

**Comment by Pub4Game** [comment]
Nice :3

**Comment by isoz** [comment]
I can't believe you still added no way for us to import old yml folder to the file or mysql... What am I suppose to do about the 30,000 players? you can't just change how things are saved from one moment to the other

**Comment by 64FF00** [comment]
@isoz I'm still on it... Btw I don't think this is the right place to discuss it

**Comment by bazza2k16** [comment]
@64ff00 any chance you've had a look at FactionsPro problem, it won't show Faction Name in chat and crashes

**Comment by AryToNeX** [comment]
Can you add health tags?  @64FF00

**Comment by xpyctum** [comment]
- [-]  te
