### ISSUE TITLE
To-do list for PureChat v1.3.0

### ISSUE THREAD

**Issue by 64FF00** [PurePlugins/PureChat#5]
### New Features
- [x] Nametag Formats
- [x] Make a option to enable or disable nametags (@xpyctum)
- [ ] Add {faction_name} and {faction_rank} tags for displaying only faction names or player faction ranks (@AryToNeX)
- [ ] Custom Prefixes (@AryToNeX)

**Comment by 64FF00** [comment]
Nametags are finally done! Woohoo!

**Comment by xpyctum** [comment]
MySQL? :angry: :angry:  :angry:

**Comment by qwefqwfqwefqwef** [comment]
Excellent!

**Comment by xpyctum** [comment]
Make nametags enabling with config file.

**Comment by 64FF00** [comment]
@xpyctum Thx, I'll add it in the next update

**Comment by 64FF00** [comment]
@AryToNeX https://github.com/PurePlugins/PureChat/issues/11

**Comment by Pub4Game** [comment]
Can add /mute? For example /mute Steve 1 day
